# 邮箱绑定插件配置文件
#
# 数据库配置
database:
  host: localhost
  port: 3306
  database: authme
  username: root
  password: wcjs123
  table: authme
  # 数据库SSL配置
  ssl: false
  ssl-mode: disabled
smtp:
  host: smtp.exmail.qq.com
  port: 465
  username: support@cnmsb.xin
  password: qTHWV9pU4fR52rGf
  ssl: true
  tls: false